export {$, PLACEHOLDER} from '@placeholder/index'
export {curry} from '@params/curry'
export {curryObjectK, curryObjectN, curryObjectKN} from '@object/index'
export {pipe} from '@fp/pipe'
export {compose} from '@fp/compose'
export {curryify} from '@params/ify'
export {version} from '../package.json'
export {K, I} from '@combinators/index'
export {remap, remapArray} from '@params/remap'
