export {$, PLACEHOLDER} from '@placeholder/index'
export {compose} from '@fp/compose'
export {pipe} from '@fp/pipe'
export {version} from '../package.json'
export {K, I} from '@combinators/index'
export {curry} from '@curry/katsu'
export {curryify} from '@curry/ify'
export {curryObjectK, curryObjectN, curryObjectKN} from '@object/index'
